sudo: false
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
before_install: 
  cpanm -n Devel::Cover::Report::Coveralls
script:
  ln -vnsf perl-mop4import-declare ../MOP4Import && cd ../MOP4Import &&
  perl Build.PL && ./Build build && cover -test
after_success:
  cover -report coveralls
