sudo: false
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
before_install: 
  cpanm -n Devel::Cover::Report::Coveralls
install:
  cpanm --installdeps --notest .
script:
  ln -vnsf perl-mop4import-declare ../MOP4Import && cd ../MOP4Import &&
  perl Build.PL && ./Build build && cover -test
after_success:
  cover -report coveralls
