language: minimal
services: docker
env:
  - image=perl:5.30
  - image=perl:5.28
  - image=perl:5.26
  - image=perl:5.24
  - image=perl:5.22
  - image=perl:5.20
  - image=perl:5.18
  - image=perl:5.16
  - image=perl:5.14
  - image=perl:5.12
  - image=perl:5.10
before_install:
  - docker pull $image
  - docker run $image perl -V
script:
  - |
    echo TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR
    echo TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
    docker run --init --rm -it -v $PWD:/$TRAVIS_REPO_SLUG -w /$TRAVIS_REPO_SLUG $image bash -c '
    set -euxo pipefail
    distDir=$PWD
    mkdir -p ../build/lib
    cd ../build
    buildRoot=$PWD
    ln -vnsfr $distDir lib/MOP4Import
    ln -vnsfr $distDir/cpanfile .
    curl -fsSL --compressed https://git.io/cpm > cpm
    chmod +x cpm
    ./cpm install Devel::Cover Devel::Cover::Report::Coveralls
    ./cpm install
    cd $distDir
    perl -I$buildRoot/local/lib/perl5 Build.PL
    perl -I$buildRoot/local/lib/perl5 Build build
    perl -I$buildRoot/local/lib/perl5 cover -test
    echo DONE
    '
after_success:
  perl -I$PWD/../build/local/lib/perl5 cover -report coveralls
