---
abstract: 'Thin Meta-Object Protocol to build extensible exporters'
author:
  - 'KOBAYASHI, Hiroaki <hkoba@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Cpanel::JSON::XS: '4.05'
  JSON::PP: '2.273'
  Module::Build::Pluggable::CPANfile: '0.05'
  Test::Exit: '0'
  Test::Kantan: '0'
  Test::More: '1.3021'
  Test::Output: '0'
  YAML::Syck: '0'
  rlib: '0'
configure_requires:
  Module::Build: '0.42'
  Module::Build::Pluggable::CPANfile: '0.05'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MOP4Import-Declare
provides:
  MOP4Import::Base::CLI:
    file: Base/CLI.pm
  MOP4Import::Base::CLI_JSON:
    file: Base/CLI_JSON.pm
  MOP4Import::Base::CLI_Opts:
    file: Base/CLI_Opts.pm
  MOP4Import::Base::Configure:
    file: Base/Configure.pm
  MOP4Import::Declare:
    file: Declare.pm
    version: '0.051'
  MOP4Import::Declare::Type:
    file: Declare/Type.pm
  MOP4Import::FieldSpec:
    file: FieldSpec.pm
  MOP4Import::NamedCodeAttributes:
    file: NamedCodeAttributes.pm
  MOP4Import::Opts:
    file: Opts.pm
  MOP4Import::PSGIEnv:
    file: PSGIEnv.pm
  MOP4Import::Pairs:
    file: Pairs.pm
  MOP4Import::Types:
    file: Types.pm
  MOP4Import::Types::Extend:
    file: Types/Extend.pm
  MOP4Import::Util:
    file: Util.pm
  MOP4Import::Util::CallTester:
    file: Util/CallTester.pm
  MOP4Import::Util::CommentedJson:
    file: Util/CommentedJson.pm
  MOP4Import::Util::FindMethods:
    file: Util/FindMethods.pm
  MOP4Import::Util::Inspector:
    file: Util/Inspector.pm
  MOP4Import::Util::JSON_TYPE:
    file: Util/JSON_TYPE.pm
  MOP4Import::Util::ResolveSymlinks:
    file: Util/ResolveSymlinks.pm
  MOP4Import::Util::compat_double_diamond:
    file: Util/compat_double_diamond.pm
  MOP4Import::Util::compat_double_diamond_5_20:
    file: Util/compat_double_diamond_5_20.pm
recommends:
  Cpanel::JSON::XS: '4.05'
  Data::Dumper: '2.160'
  File::AddInc: '0'
  Module::Runtime: '0'
  YAML::Syck: '0'
requires:
  JSON::MaybeXS: '0'
  Sub::Util: '1.40'
  perl: '5.010'
  rlib: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/hkoba/perl-mop4import-declare
version: '0.051'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
