---
abstract: 'Thin Meta-Object Protocol to build extensible exporters'
author:
  - 'KOBAYASHI, Hiroaki <hkoba@cpan.org>'
build_requires:
  Module::Build::Pluggable::CPANfile: '0.05'
  Test::Kantan: '0'
  rlib: '0'
configure_requires:
  Module::Build: '0.42'
  Module::Build::Pluggable: '0'
  Module::Build::Pluggable::CPANfile: '0.05'
  Module::CPANfile: '0'
  rlib: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MOP4Import-Declare
provides:
  MOP4Import::Base::CLI:
    file: Base/CLI.pm
  MOP4Import::Base::Configure:
    file: Base/Configure.pm
  MOP4Import::Declare:
    file: Declare.pm
    version: '0.004'
  MOP4Import::Declare::Type:
    file: Declare/Type.pm
  MOP4Import::FieldSpec:
    file: FieldSpec.pm
  MOP4Import::Opts:
    file: Opts.pm
  MOP4Import::PSGIEnv:
    file: PSGIEnv.pm
  MOP4Import::Pairs:
    file: Pairs.pm
  MOP4Import::Types:
    file: Types.pm
  MOP4Import::Types::Extend:
    file: Types/Extend.pm
  MOP4Import::Util:
    file: Util.pm
  MOP4Import::Util::FindMethods:
    file: Util/FindMethods.pm
requires:
  perl: '5.010'
  rlib: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.004'
